#!/bin/bash
# Deletes every Kubernetes Service of type=LoadBalancer so AWS Cloud
# Controller Manager (CCM) issues the matching ELBv2 DeleteLoadBalancer
# call for the NLB/ALB it provisioned — BEFORE terraform destroy removes
# the nodes CCM needs to be running on to do that cleanup.
#
# WHY THIS IS NEEDED:
#   Every load balancer CCM creates for a LoadBalancer-type Service is not
#   a Terraform-managed resource — Terraform never sees its ARN, so
#   `terraform destroy` has no way to remove it. CCM is the only thing
#   that can delete it, and CCM can only react to `kubectl delete svc`
#   while its own pod (on the master) and the target nodes are still
#   alive. Destroy nodes first and the load balancer is orphaned in AWS:
#   it keeps billing and can block VPC/subnet deletion later.
#
#
# Waits for the matching load balancer to actually disappear on the AWS
# side (filtered by the kubernetes.io/cluster/<cluster_name>=owned tag
# CCM stamps on everything it creates — same tag convention already used
# on ASG/instance/route-table resources elsewhere in this repo), not just
# for `kubectl get svc` to return nothing — the Service can vanish from
# the API before CCM's DeleteLoadBalancer call actually completes.
#
# Always exits 0 — a stuck load balancer should not block terraform
# destroy from proceeding. The caller (GitHub Actions step) surfaces the
# warning so it can be cleaned up manually if needed.
set -uo pipefail
export KUBECONFIG=/home/ec2-user/.kube/config
export PATH=$PATH:/usr/local/bin

CLUSTER_NAME="__CLUSTER_NAME__"

IMDS_TOKEN=$(curl -s -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
AWS_REGION=$(curl -s -H "X-aws-ec2-metadata-token: $IMDS_TOKEN" http://169.254.169.254/latest/meta-data/placement/region)

command -v jq >/dev/null 2>&1 || { echo "ERROR: jq is required." >&2; exit 0; }

echo "=== Discovering type=LoadBalancer Services ==="
LB_SVCS=$(kubectl get svc --all-namespaces -o json 2>/dev/null \
  | jq -r '.items[] | select(.spec.type=="LoadBalancer") | "\(.metadata.namespace)/\(.metadata.name)"')

if [ -n "$LB_SVCS" ]; then
  echo "LoadBalancer Services: $(echo "$LB_SVCS" | tr '\n' ' ')"
  for svc in $LB_SVCS; do
    ns="${svc%%/*}"; name="${svc##*/}"

    # ── Gateway API check ──────────────────────────────────────────────
    # If this Service was generated by a Gateway API `Gateway` object,
    # deleting the Service alone is pointless — cilium-operator's
    # controller will just recreate it (own reconcile loop, independent
    # of ArgoCD/freeze-argocd.sh). Delete the owning Gateway instead so
    # Kubernetes garbage-collects the Service and nothing recreates it.
    OWNER_KIND=$(kubectl get svc "$name" -n "$ns" -o jsonpath='{.metadata.ownerReferences[0].kind}' 2>/dev/null || true)
    OWNER_NAME=$(kubectl get svc "$name" -n "$ns" -o jsonpath='{.metadata.ownerReferences[0].name}' 2>/dev/null || true)

    if [ "$OWNER_KIND" = "Gateway" ] && [ -n "$OWNER_NAME" ]; then
      echo "svc/$name -n $ns is owned by Gateway/$OWNER_NAME — deleting the Gateway instead of the Service"
      echo "(deleting the Service alone would just have cilium-operator recreate it; this also orphans any HTTPRoute attached to it, which is expected during a full cluster teardown)"
      kubectl delete gateway "$OWNER_NAME" -n "$ns" --wait=false || true
    else
      echo "Deleting svc/$name -n $ns (triggers CCM's ELBv2 DeleteLoadBalancer)..."
      kubectl delete svc "$name" -n "$ns" --wait=false || true
    fi
  done
else
  echo "No LoadBalancer Services found in-cluster — checking AWS directly in case one was already deleted (e.g. via a namespace cascade) and may still be mid-teardown."
fi

# ── Confirm no LoadBalancer Service came back ─────────────────────────────
# Guards against any other controller (not just Gateway API) recreating a
# Service after we deleted it. If one reappears, log it loudly rather than
# silently racing straight into the AWS-side poll below.
echo "=== Verifying no LoadBalancer Service has reappeared (10s settle check) ==="
sleep 10
STILL_PRESENT=$(kubectl get svc --all-namespaces -o json 2>/dev/null \
  | jq -r '.items[] | select(.spec.type=="LoadBalancer") | "\(.metadata.namespace)/\(.metadata.name)"')
if [ -n "$STILL_PRESENT" ]; then
  echo "WARNING: LoadBalancer Service(s) still present (or recreated) after delete: $(echo "$STILL_PRESENT" | tr '\n' ' ')"
  echo "If these are Gateway-owned, confirm the owning Gateway was actually deleted (kubectl get gateway -A)."
else
  echo "Confirmed: no LoadBalancer Services remain in-cluster."
fi

# ALWAYS run — a Service can vanish from the API before CCM's
# DeleteLoadBalancer call actually completes, regardless of how it was deleted.
echo "=== Waiting for CCM to remove any load balancer tagged for this cluster (up to 6 minutes) ==="
for i in $(seq 1 36); do
  STILL_OURS=$(aws elbv2 describe-load-balancers --region "$AWS_REGION" --output json 2>/dev/null \
    | jq -r '.LoadBalancers[].LoadBalancerArn' \
    | while read -r arn; do
        aws elbv2 describe-tags --region "$AWS_REGION" --resource-arns "$arn" --output json 2>/dev/null \
          | jq -e --arg cn "$CLUSTER_NAME" \
            '.TagDescriptions[0].Tags[]? | select(.Key=="kubernetes.io/cluster/\($cn)" and .Value=="owned")' >/dev/null \
          && echo "$arn"
      done)

  # Classic ELBs (CLB) live under a separate API (`aws elb`, not `aws
  # elbv2`) and are invisible to the ALB/NLB check above. A plain
  # type=LoadBalancer Service with no aws-load-balancer-type annotation
  # defaults to a Classic ELB under cloud-provider-aws, so this repo can
  # produce them even though the ALB module itself only uses ALB/NLB.
  # Without this check, a lingering/mid-delete Classic ELB is silently
  # invisible to this loop and the script reports "all clear" while it's
  # still there.
  STILL_OURS_CLASSIC=$(aws elb describe-load-balancers --region "$AWS_REGION" --output json 2>/dev/null \
    | jq -r '.LoadBalancerDescriptions[].LoadBalancerName' \
    | while read -r lbname; do
        aws elb describe-tags --region "$AWS_REGION" --load-balancer-names "$lbname" --output json 2>/dev/null \
          | jq -e --arg cn "$CLUSTER_NAME" \
            '.TagDescriptions[0].Tags[]? | select(.Key=="kubernetes.io/cluster/\($cn)" and .Value=="owned")' >/dev/null \
          && echo "$lbname"
      done)

  if [ -z "$STILL_OURS" ] && [ -z "$STILL_OURS_CLASSIC" ]; then
    echo "All CCM-provisioned load balancers for this cluster are gone."
    exit 0
  fi
  echo "  Still present (attempt $i/36): ALB/NLB=[${STILL_OURS:-none}] Classic=[${STILL_OURS_CLASSIC:-none}]"
  sleep 10
done

echo "WARNING: some load balancers tagged for this cluster are still present after 6 minutes:"
echo "ALB/NLB: $STILL_OURS"
echo "Classic: $STILL_OURS_CLASSIC"
echo "Check the AWS Console/CLI (ELBv2 and Classic ELB) and delete manually if needed — terraform destroy will not remove them."
exit 0
