# Queries the official AWS SSM path for the latest standard AL2023 AMI ID
data "aws_ssm_parameter" "amazon_linux_2023" {
  name = "/aws/service/ami-amazon-linux-latest/al2023-ami-minimal-kernel-default-x86_64"
}

# ── SSM Parameter for Join Token ──────────────────────────────────────────────
resource "aws_ssm_parameter" "cluster_join_token" {
  name        = "/${var.env}/k8s/join_token"
  description = "Token dynamically generated by Master for Worker nodes to join cluster"
  type        = "SecureString"
  value       = "placeholder-awaiting-master-initialization"

  lifecycle {
    ignore_changes = [value]
  }
}

# ── Security group: Master ─────────────────────────────────────────────────────
resource "aws_security_group" "master" {
  name        = "${var.env}-k8s-master-sg"
  description = "K8s master node"
  vpc_id      = var.vpc_id

  lifecycle {
    ignore_changes = [ingress, egress]
  }

  tags = { Name = "${var.env}-k8s-master-sg" }
}

# ── Security group: Worker ─────────────────────────────────────────────────────
resource "aws_security_group" "worker" {
  name        = "${var.env}-k8s-worker-sg"
  description = "K8s worker nodes"
  vpc_id      = var.vpc_id

  lifecycle {
    ignore_changes = [ingress, egress]
  }

  tags = { Name = "${var.env}-k8s-worker-sg" }
}

# ── Master rules ───────────────────────────────────────────────────────────────
resource "aws_security_group_rule" "master_ingress_from_worker" {
  description              = "All traffic from workers"
  type                     = "ingress"
  from_port                = 0
  to_port                  = 0
  protocol                 = "-1"
  security_group_id        = aws_security_group.master.id
  source_security_group_id = aws_security_group.worker.id
}

resource "aws_security_group_rule" "master_ingress_self" {
  description       = "All traffic from other masters (self)"
  type              = "ingress"
  from_port         = 0
  to_port           = 0
  protocol          = "-1"
  security_group_id = aws_security_group.master.id
  self              = true
}

resource "aws_security_group_rule" "master_ingress_ssh" {
  description       = "SSH from anywhere"
  type              = "ingress"
  from_port         = 22
  to_port           = 22
  protocol          = "tcp"
  security_group_id = aws_security_group.master.id
  cidr_blocks       = ["0.0.0.0/0"]
}

resource "aws_security_group_rule" "master_ingress_api_from_trusted_cidrs" {
  count             = length(var.trusted_api_cidr_blocks) > 0 ? 1 : 0
  description       = "kube-apiserver from trusted CIDRs (e.g. hub VPC via Transit Gateway)"
  type              = "ingress"
  from_port         = 6443
  to_port           = 6443
  protocol          = "tcp"
  security_group_id = aws_security_group.master.id
  cidr_blocks       = var.trusted_api_cidr_blocks
}

resource "aws_security_group_rule" "master_egress_all" {
  description       = "All outbound"
  type              = "egress"
  from_port         = 0
  to_port           = 0
  protocol          = "-1"
  security_group_id = aws_security_group.master.id
  cidr_blocks       = ["0.0.0.0/0"]
}

# ── Worker rules ───────────────────────────────────────────────────────────────
resource "aws_security_group_rule" "worker_ingress_from_master" {
  description              = "All traffic from master"
  type                     = "ingress"
  from_port                = 0
  to_port                  = 0
  protocol                 = "-1"
  security_group_id        = aws_security_group.worker.id
  source_security_group_id = aws_security_group.master.id
}

resource "aws_security_group_rule" "worker_ingress_self" {
  description       = "All traffic between workers (self)"
  type              = "ingress"
  from_port         = 0
  to_port           = 0
  protocol          = "-1"
  security_group_id = aws_security_group.worker.id
  self              = true
}

resource "aws_security_group_rule" "worker_ingress_nodeport" {
  description              = "NodePort range from ALB"
  type                     = "ingress"
  from_port                = 30000
  to_port                  = 32767
  protocol                 = "tcp"
  security_group_id        = aws_security_group.worker.id
  source_security_group_id = var.alb_sg_id
}

resource "aws_security_group_rule" "worker_ingress_ssh" {
  description       = "SSH from VPC"
  type              = "ingress"
  from_port         = 22
  to_port           = 22
  protocol          = "tcp"
  security_group_id = aws_security_group.worker.id
  cidr_blocks       = ["10.0.0.0/16"]
}

resource "aws_security_group_rule" "worker_egress_all" {
  description       = "All outbound"
  type              = "egress"
  from_port         = 0
  to_port           = 0
  protocol          = "-1"
  security_group_id = aws_security_group.worker.id
  cidr_blocks       = ["0.0.0.0/0"]
}

# ── IAM role: master ───────────────────────────────────────────────────────────
resource "aws_iam_role" "master" {
  name = "${var.env}-k8s-master-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "ec2.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })

  tags = { Name = "${var.env}-k8s-master-role", Env = var.env }
}

resource "aws_iam_role_policy" "master_ssm_write" {
  name = "${var.env}-k8s-master-ssm-write-policy"
  role = aws_iam_role.master.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Sid      = "SSMWriteToken"
      Effect   = "Allow"
      Action   = ["ssm:PutParameter"]
      Resource = aws_ssm_parameter.cluster_join_token.arn
    }]
  })
}

resource "aws_iam_role_policy" "master_ccm_policy" {
  name = "${var.env}-k8s-master-ccm-policy"
  role = aws_iam_role.master.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = [
          "ec2:DescribeInstances",
          "ec2:DescribeRegions",
          "ec2:DescribeRouteTables",
          "ec2:DescribeSecurityGroups",
          "ec2:DescribeSubnets",
          "ec2:DescribeVolumes",
          "ec2:CreateSecurityGroup",
          "ec2:CreateTags",
          "ec2:DeleteSecurityGroup",
          "ec2:ModifyInstanceAttribute",
          "ec2:AuthorizeSecurityGroupIngress",
          "ec2:RevokeSecurityGroupIngress",
          "ec2:DescribeAvailabilityZones",
          "ec2:DescribeInstanceTopology"
        ]
        Resource = "*"
      }
    ]
  })
}

resource "aws_iam_instance_profile" "master" {
  name = "${var.env}-k8s-master-profile"
  role = aws_iam_role.master.name
}

# ── IAM role: worker (used by ASG launch template) ────────────────────────────
resource "aws_iam_role" "worker" {
  name = "${var.env}-k8s-worker-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "ec2.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })

  tags = { Name = "${var.env}-k8s-worker-role", Env = var.env }
}

resource "aws_iam_role_policy" "worker_ebs" {
  name = "${var.env}-k8s-worker-ebs-policy"
  role = aws_iam_role.worker.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "EBSForPVC"
        Effect = "Allow"
        Action = [
          "ec2:AttachVolume", "ec2:CreateVolume", "ec2:DeleteVolume",
          "ec2:DetachVolume", "ec2:DescribeVolumes", "ec2:DescribeVolumeStatus",
          "ec2:DescribeInstances", "ec2:CreateSnapshot", "ec2:DeleteSnapshot",
          "ec2:DescribeSnapshots", "ec2:CreateTags", "ec2:ModifyVolume",
          "ec2:DescribeAvailabilityZones"
        ]
        Resource = "*"
      },
      {
        Sid      = "S3Access"
        Effect   = "Allow"
        Action   = ["s3:GetObject", "s3:PutObject", "s3:DeleteObject", "s3:ListBucket"]
        Resource = "*"
      },
      {
        Sid      = "SSMReadToken"
        Effect   = "Allow"
        Action   = ["ssm:GetParameter"]
        Resource = aws_ssm_parameter.cluster_join_token.arn
      }
    ]
  })
}

# ASG permissions — Cluster Autoscaler runs on master and needs these
resource "aws_iam_role_policy" "master_autoscaler" {
  name = "${var.env}-k8s-master-autoscaler-policy"
  role = aws_iam_role.master.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Sid    = "ClusterAutoscaler"
      Effect = "Allow"
      Action = [
        "autoscaling:DescribeAutoScalingGroups",
        "autoscaling:DescribeAutoScalingInstances",
        "autoscaling:DescribeLaunchConfigurations",
        "autoscaling:DescribeScalingActivities",
        "autoscaling:SetDesiredCapacity",
        "autoscaling:TerminateInstanceInAutoScalingGroup",
        "ec2:DescribeLaunchTemplateVersions",
        "ec2:DescribeInstanceTypes"
      ]
      Resource = "*"
    }]
  })
}

resource "aws_iam_instance_profile" "worker" {
  name = "${var.env}-k8s-worker-profile"
  role = aws_iam_role.worker.name
}

# ── Master node ────────────────────────────────────────────────────────────────
resource "aws_instance" "master" {
  ami                         = data.aws_ssm_parameter.amazon_linux_2023.value
  instance_type               = var.master_instance_type
  subnet_id                   = var.public_subnet_ids[0]
  private_ip                  = var.master_private_ip
  associate_public_ip_address = true
  vpc_security_group_ids      = [aws_security_group.master.id]
  key_name                    = var.key_name
  iam_instance_profile        = aws_iam_instance_profile.master.name
  user_data                   = var.k8s_bootstrap

  root_block_device {
    volume_size = 15
    volume_type = "gp3"
  }

  tags = { Name = "${var.env}-k8s-master", Role = "master", Env = var.env, "kubernetes.io/cluster/${var.cluster_name}" = "owned" }
}
