# ── SSM Parameter for Join Token ──────────────────────────────────────────────
resource "aws_ssm_parameter" "cluster_join_token" {
  name        = "/${var.env}/k8s/join_token"
  description = "Token dynamically generated by Master for Worker nodes to join cluster"
  type        = "SecureString"
  value       = "placeholder-awaiting-master-initialization"

  lifecycle {
    ignore_changes = [value]
  }
}

# ── Security group: Master ─────────────────────────────────────────────────────
resource "aws_security_group" "master" {
  name        = "${var.env}-k8s-master-sg"
  description = "K8s master node"
  vpc_id      = var.vpc_id

  lifecycle {
    ignore_changes = [ingress, egress]
  }

  tags = { Name = "${var.env}-k8s-master-sg" }
}

# ── Security group: Worker ─────────────────────────────────────────────────────
resource "aws_security_group" "worker" {
  name        = "${var.env}-k8s-worker-sg"
  description = "K8s worker nodes"
  vpc_id      = var.vpc_id

  lifecycle {
    ignore_changes = [ingress, egress]
  }

  tags = { Name = "${var.env}-k8s-worker-sg" }
}

# ── Master rules ───────────────────────────────────────────────────────────────
resource "aws_security_group_rule" "master_ingress_from_worker" {
  description              = "All traffic from workers"
  type                     = "ingress"
  from_port                = 0
  to_port                  = 0
  protocol                 = "-1"
  security_group_id        = aws_security_group.master.id
  source_security_group_id = aws_security_group.worker.id
}

resource "aws_security_group_rule" "master_ingress_self" {
  description       = "All traffic from other masters (self)"
  type              = "ingress"
  from_port         = 0
  to_port           = 0
  protocol          = "-1"
  security_group_id = aws_security_group.master.id
  self              = true
}

resource "aws_security_group_rule" "master_ingress_ssh" {
  description       = "SSH from anywhere"
  type              = "ingress"
  from_port         = 22
  to_port           = 22
  protocol          = "tcp"
  security_group_id = aws_security_group.master.id
  cidr_blocks       = ["0.0.0.0/0"]
}

resource "aws_security_group_rule" "master_ingress_api_from_trusted_cidrs" {
  count             = length(var.trusted_api_cidr_blocks) > 0 ? 1 : 0
  description       = "kube-apiserver from trusted CIDRs (e.g. hub VPC via Transit Gateway)"
  type              = "ingress"
  from_port         = 6443
  to_port           = 6443
  protocol          = "tcp"
  security_group_id = aws_security_group.master.id
  cidr_blocks       = var.trusted_api_cidr_blocks
}

resource "aws_security_group_rule" "master_egress_all" {
  description       = "All outbound"
  type              = "egress"
  from_port         = 0
  to_port           = 0
  protocol          = "-1"
  security_group_id = aws_security_group.master.id
  cidr_blocks       = ["0.0.0.0/0"]
}

# ── Worker rules ───────────────────────────────────────────────────────────────
resource "aws_security_group_rule" "worker_ingress_from_master" {
  description              = "All traffic from master"
  type                     = "ingress"
  from_port                = 0
  to_port                  = 0
  protocol                 = "-1"
  security_group_id        = aws_security_group.worker.id
  source_security_group_id = aws_security_group.master.id
}

resource "aws_security_group_rule" "worker_ingress_self" {
  description       = "All traffic between workers (self)"
  type              = "ingress"
  from_port         = 0
  to_port           = 0
  protocol          = "-1"
  security_group_id = aws_security_group.worker.id
  self              = true
}

resource "aws_security_group_rule" "worker_ingress_nodeport" {
  description              = "NodePort range from ALB"
  type                     = "ingress"
  from_port                = 30000
  to_port                  = 32767
  protocol                 = "tcp"
  security_group_id        = aws_security_group.worker.id
  source_security_group_id = var.alb_sg_id
}

resource "aws_security_group_rule" "worker_ingress_ssh" {
  description       = "SSH from VPC"
  type              = "ingress"
  from_port         = 22
  to_port           = 22
  protocol          = "tcp"
  security_group_id = aws_security_group.worker.id
  cidr_blocks       = ["10.0.0.0/16"]
}

resource "aws_security_group_rule" "worker_egress_all" {
  description       = "All outbound"
  type              = "egress"
  from_port         = 0
  to_port           = 0
  protocol          = "-1"
  security_group_id = aws_security_group.worker.id
  cidr_blocks       = ["0.0.0.0/0"]
}

# ── IAM role: master ───────────────────────────────────────────────────────────
resource "aws_iam_role" "master" {
  name = "${var.env}-k8s-master-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "ec2.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })

  tags = { Name = "${var.env}-k8s-master-role", Env = var.env }
}

resource "aws_iam_role_policy" "master_ssm_write" {
  name = "${var.env}-k8s-master-ssm-write-policy"
  role = aws_iam_role.master.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Sid      = "SSMWriteToken"
      Effect   = "Allow"
      Action   = ["ssm:PutParameter"]
      Resource = aws_ssm_parameter.cluster_join_token.arn
    }]
  })
}

resource "aws_iam_role_policy" "master_ccm_policy" {
  name = "${var.env}-k8s-master-ccm-policy"
  role = aws_iam_role.master.id

  # NOTE ON SCOPING: EC2's Describe* actions don't support resource-level
  # permissions at all (AWS IAM limitation, not something Terraform/HCL can
  # work around) — Resource "*" is unavoidable for those. The *mutating*
  # actions below ARE scoped: they're conditioned on the resource carrying
  # this cluster's ownership tag, so this role can't touch security groups
  # or instances belonging to a different cluster in the same account.
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "ReadOnlyDescribe"
        Effect = "Allow"
        Action = [
          "ec2:DescribeInstances",
          "ec2:DescribeRegions",
          "ec2:DescribeRouteTables",
          "ec2:DescribeSecurityGroups",
          "ec2:DescribeSubnets",
          "ec2:DescribeVolumes",
          "ec2:DescribeAvailabilityZones",
          "ec2:DescribeInstanceTopology"
        ]
        Resource = "*"
      },
      {
        Sid      = "CreateSecurityGroupTaggedForThisCluster"
        Effect   = "Allow"
        Action   = "ec2:CreateSecurityGroup"
        Resource = "*"
        Condition = {
          StringEquals = {
            "aws:RequestTag/kubernetes.io/cluster/${var.cluster_name}" = "owned"
          }
        }
      },
      {
        Sid    = "MutateOnlyResourcesTaggedForThisCluster"
        Effect = "Allow"
        Action = [
          "ec2:CreateTags",
          "ec2:DeleteSecurityGroup",
          "ec2:ModifyInstanceAttribute",
          "ec2:AuthorizeSecurityGroupIngress",
          "ec2:RevokeSecurityGroupIngress"
        ]
        Resource = "*"
        Condition = {
          StringEquals = {
            "aws:ResourceTag/kubernetes.io/cluster/${var.cluster_name}" = "owned"
          }
        }
      }
    ]
  })
}

resource "aws_iam_instance_profile" "master" {
  name = "${var.env}-k8s-master-profile"
  role = aws_iam_role.master.name
}

# ── IAM role: worker (used by ASG launch template) ────────────────────────────
resource "aws_iam_role" "worker" {
  name = "${var.env}-k8s-worker-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "ec2.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })

  tags = { Name = "${var.env}-k8s-worker-role", Env = var.env }
}

resource "aws_iam_role_policy" "worker_ebs" {
  name = "${var.env}-k8s-worker-ebs-policy"
  role = aws_iam_role.worker.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = concat(
      [
        {
          Sid    = "EBSForPVC"
          Effect = "Allow"
          Action = [
            "ec2:AttachVolume", "ec2:CreateVolume", "ec2:DeleteVolume",
            "ec2:DetachVolume", "ec2:DescribeVolumes", "ec2:DescribeVolumeStatus",
            "ec2:DescribeInstances", "ec2:CreateSnapshot", "ec2:DeleteSnapshot",
            "ec2:DescribeSnapshots", "ec2:CreateTags", "ec2:ModifyVolume",
            "ec2:DescribeAvailabilityZones"
          ]
          Resource = "*"
        },
        {
          Sid      = "SSMReadToken"
          Effect   = "Allow"
          Action   = ["ssm:GetParameter"]
          Resource = aws_ssm_parameter.cluster_join_token.arn
        }
      ],
      # S3 access is scoped to the specific buckets this cluster owns,
      # passed in from the root module — never a account-wide wildcard.
      # If no buckets are passed (e.g. the hub cluster), this statement
      # is simply omitted rather than falling back to Resource "*".
      length(var.s3_bucket_arns) > 0 ? [
        {
          Sid    = "S3Access"
          Effect = "Allow"
          Action = ["s3:GetObject", "s3:PutObject", "s3:DeleteObject", "s3:ListBucket"]
          Resource = flatten([
            var.s3_bucket_arns,
            [for arn in var.s3_bucket_arns : "${arn}/*"]
          ])
        }
      ] : []
    )
  })
}

# ASG permissions — Cluster Autoscaler runs on master and needs these
resource "aws_iam_role_policy" "master_autoscaler" {
  name = "${var.env}-k8s-master-autoscaler-policy"
  role = aws_iam_role.master.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Sid    = "ClusterAutoscaler"
      Effect = "Allow"
      Action = [
        "autoscaling:DescribeAutoScalingGroups",
        "autoscaling:DescribeAutoScalingInstances",
        "autoscaling:DescribeLaunchConfigurations",
        "autoscaling:DescribeScalingActivities",
        "autoscaling:SetDesiredCapacity",
        "autoscaling:TerminateInstanceInAutoScalingGroup",
        "ec2:DescribeLaunchTemplateVersions",
        "ec2:DescribeInstanceTypes"
      ]
      Resource = "*"
    }]
  })
}

resource "aws_iam_instance_profile" "worker" {
  name = "${var.env}-k8s-worker-profile"
  role = aws_iam_role.worker.name
}

# ── Master node ────────────────────────────────────────────────────────────────
resource "aws_instance" "master" {
  # AMI is the shared, Packer-built k8s base image (containerd/kubeadm/
  # kubelet/kubectl + node prep baked in) — see /packer and modules/ami.
  # No dynamic SSM lookup here anymore, so both this instance and every
  # worker launched by modules/asg come from the exact same image.
  ami                         = var.ami_id
  instance_type               = var.master_instance_type
  subnet_id                   = var.public_subnet_ids[0]
  private_ip                  = var.master_private_ip
  associate_public_ip_address = true
  vpc_security_group_ids      = [aws_security_group.master.id]
  key_name                    = var.key_name
  iam_instance_profile        = aws_iam_instance_profile.master.name
  user_data                   = var.k8s_bootstrap

  root_block_device {
    volume_size = 15
    volume_type = "gp3"
  }

  tags = { Name = "${var.env}-k8s-master", Role = "master", Env = var.env, "kubernetes.io/cluster/${var.cluster_name}" = "owned" }
}
